Added the option to create password protected .zip files in New-WindowsFromGoldenImage for KVM type images
ader1990/windows-openstack-imaging-tools pull request #1
Opened 2016-11-21 14:38 UTC by andreitira

2016-11-21 15:02 UTC, ader1990 requested changes
a few naming and PowerShell style issues, the logic is good

2016-11-21 15:02 UTC, ader1990 commented on WinImageBuilder.psm1
> +function Create-ProtectedZip {
Leave the method name unchanged Start-WindowsCommand and use the alias param when you use it.

2016-11-21 15:02 UTC, ader1990 commented on WinImageBuilder.psm1
> +                If ($zipPassword){
if*

2016-11-21 15:02 UTC, ader1990 commented on WinImageBuilder.psm1
> +                    $final_path=$barePath + ".zip"
zipPath

2016-11-21 15:02 UTC, ader1990 commented on WinImageBuilder.psm1
> +                    $final_path=$barePath + ".zip"
plus make sure indentation is correct

2016-11-21 16:26 UTC, costingalan commented
@andreitira: I think we need to write the password after the zip was created so that it will be easy to copy it.

2016-11-21 16:34 UTC, costingalan commented
I suggest you add:

- [ ] Information in the README.md file.
- [ ] Possibility to create password protected files when using New-WindowsOnlineImage, New-MAASImage and also New-WindowsCloudImage.
- [ ] Add the $zipPassword as an optional parameter to the above functions.

2016-11-22 08:52 UTC, andreitira commented
Made all the requested changes :)
Please take a look at my implementation for New-WindowsCloudImage. Im a bit uncertain about that one.

2016-11-25 09:57 UTC, closed without merging